### ISSUE TITLE
`register_clients` dead in some versions of Lambda sandboxes

### ISSUE THREAD

**Issue by ngr** [sosw/sosw#313]
```
[ERROR] RuntimeError: Failed to import for service s3. Component naming problem.
Traceback (most recent call last):
  File "/opt/python/sosw/app.py", line 449, in lambda_handler
    global_vars.processor = processor_class(custom_config=custom_config, test=test)
  File "/var/task/app.py", line 182, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/python/sosw/app.py", line 81, in __init__
    self.register_clients(self.config.get('init_clients', []))
  File "/opt/python/sosw/components/benchmark.py", line 48, in _timing_and_call_counter
    r = fn(self, *a, **kw)
  File "/opt/python/sosw/app.py", line 151, in register_clients
    raise RuntimeError(f"Failed to import for service {module_name}. Component naming problem.")
```

**Comment by ngr** [comment]
```
[ERROR] ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/opt/python/botocore/utils.py)
Traceback (most recent call last):
  File "/opt/python/sosw/app.py", line 449, in lambda_handler
    global_vars.processor = processor_class(custom_config=custom_config, test=test)
  File "/var/task/app.py", line 182, in __init__
    setattr(self, 's3_client', boto3.client('s3'))
  File "/var/lang/lib/python3.11/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/var/lang/lib/python3.11/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/opt/python/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/opt/python/botocore/client.py", line 144, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/opt/python/botocore/client.py", line 197, in _create_client_class
    self._event_emitter.emit(
  File "/opt/python/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/python/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/opt/python/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/var/lang/lib/python3.11/site-packages/boto3/utils.py", line 65, in _handler
    module = import_module(module)
  File "/var/lang/lib/python3.11/site-packages/boto3/utils.py", line 56, in import_module
    __import__(name)
  File "/var/lang/lib/python3.11/site-packages/boto3/s3/inject.py", line 18, in <module>
    from boto3.s3.transfer import (
  File "/var/lang/lib/python3.11/site-packages/boto3/s3/transfer.py", line 134, in <module>
    from s3transfer.futures import NonThreadedExecutor
  File "/var/lang/lib/python3.11/site-packages/s3transfer/futures.py", line 22, in <module>
    from s3transfer.utils import FunctionContainer, TaskSemaphore
  File "/var/lang/lib/python3.11/site-packages/s3transfer/utils.py", line 26, in <module>
    from botocore.utils import is_s3express_bucket
```
